### ISSUE TITLE
Confusion on <popsfile>.0 in Realtime

### ISSUE THREAD

**Issue by AndrewReynoso** [ghb24/NECI_STABLE#15]
I am trying to run NECI with a realtime block to simulate the dynamics of the 2D Hubbard model, but I am having issues with the relevant popsfile. I am confused as to where the stated "\<popsfile\>.0" file in the documentation originates; when running kmneci, I did not find it automatically generated. I would greatly appreciate any clarification on where this file is intended to come from, as I am experiencing errors (I have copied the popsfile from the build/bin folder into the src folder with the name "popsfile.0.h5" as an attempt to resolve this and said file is read, yielding a "mismatched sign length" error, whereas previously kmneci could not find a relevant popsfile).

Input:
```

# define hubbard model
  system hubbard k-space
    electrons 4
    nonuniformrandexcits pchb delocalised
    lattice square 2 2
    U 0.1
    B 1
  endsys

  calc
    readpops
    nmcyc 10000
    # for reproducibility
    seed 8
    
    totalWalkers 50000
    
    diagShift 0
    truncInitiator
    tau-values \
        start from-popsfile

    # use the initiator method
    truncinitiator
    addtoinitiator 3

    methods
      method vertex fcimc
    endmethods

  endcalc
  
  realtime 
    greater 11 11
    noshift
    dynamic-rotation
    stabilize-walkers
    rt-pops  
  endrealtime

  logging
    hdf5-pops
    popsfile
  endlog
end
```

**Comment by mcocdawc** [comment]
Hello Andrew,

Thank you for your interest.

A quick caveat in the beginning. I never worked with the real-time propagation code myself, neither as a user nor a developer. Unfortunately the one who wrote it as a PhD student left the group (and academia).

You can think of the `popsfile` as the CI vector of a state.
You would prepare this in advance from a "normal", i.e. purely imaginary time, converged calculation in `mneci` or `kmneci`. This is then an input for the real-time propagation. It should be in the same directory where you start the calculation.
Alternatively you can also use the keyword `start-hf` in the `realtime` block to directly start from a single starting determinant (usually Hartree Fock). This would fix your crash but most likely makes no sense chemically.

I will ask a bit around for people who use the realtime code and can give you better help.

**Comment by AndrewReynoso** [comment]
Thank you for the help! I think my confusion pertains more to the difference between popsfile.h5 and popsfile.0.h5. My current attempt consists of (1) running mpirun -n 1 mneci \<input\>.inp (2) renaming the output file popsfile.h5 -> popsfile.0.h5 (in the bin directory, where I am performing the calculation) (3) running mpirun -n 1 kmneci \<input'\>.inp (where the new input .inp file now contains the realtime block, i.e. it is equivalent to the previously posted .inp file). The error appears as follows:
```
========== Reading in from HDF5 popsfile ==========
 File name: popsfile.0.h5
 Previous calculation
 Date: 2024-08-12 17:36:39
 Sequence no.:           8
 VCS ver: 558e88c5ae6c30d0505a9badbc69111be0866ba1
 Build config: cmake-GNU--RELEASE
 Build date: Jul 15 2024
 Build time: 23:36:00

 ERROR.
 NECI stops in subroutine: read_walkers
 Reason:                   Mismatched sign length
 Processor:                    0
 EXITING...
```
Any guidance would be greatly appreciated!

**Comment by AndrewReynoso** [comment]
I managed to eliminate the error and run kmneci; I did this by having a separate .inp file as an input to mneci which generates popsfile.h5 (which is then renamed to popsfile.0.h5) before running the .inp file with kmneci I quoted in my first post.
The .inp file fed to mneci does not have 'readpops' in the calc block, and instead has 'start user-defined' for tau-values. Hopefully this makes sense.

**Comment by mcocdawc** [comment]
Hello Andrew,

That is what I meant by

> You would prepare this in advance from a "normal", i.e. purely imaginary time, converged calculation in mneci or kmneci.

I am sorry that I was not clear enough there.

For this preliminary calculation I would definitely enable the tau-search.
Otherwise you might have an unnecessarily slow calculation.
```text
tau-search \
    algorithm conventional \
    stop-condition 500 \
    maxWalkerBloom 2
```

In addition, I don't know if you do this already, but it is very much advised to monitor the convergence, by looking
at the data in `fciqmc_stats`.
In particular the projected energy (`Tot ProjE`) and population, i.e. number of walkers (`Parts`).
These should be visually converged, before you write the popsfile.

I will close the issue for now, but feel free to reopen if you have more questions.
