### ISSUE TITLE
Unclear/no license

### ISSUE THREAD

**Issue by mbanck** [ghb24/NECI_STABLE#2]
The top-level ```README.md``` has a copyright notice ("Copyright (c) 2013, Ali Alavi"), but no license. As NECI was mentioned in the recent PySCF paper (https://arxiv.org/abs/1701.08223), it would be good to clarify whether NECI has a similar license to PySCF or not; or rather, it would be good in general to clarify the license.

**Comment by mcocdawc** [comment]
At least of today (3 years later :-/) it has GPLv3.
