### ISSUE TITLE
Cant built with gcc 10

### ISSUE THREAD

**Issue by Standazwicky** [ghb24/NECI_STABLE#4]
Hi,
I'am trying to compile, using CMake. An I am getting this error:

`NECI_STABLE/src/DetCalc.F90:241:65:

  151 |             CALL GENEXCIT(FDET,iExcitLevel,NBASIS,NEL,0,(/0.0_dp/),NDET,1,G1,.TRUE.,NBASISMAX,.TRUE.)
      |                                                        2         
......
  241 |             CALL GENEXCIT(FDET,iExcitLevel,NBASIS,NEL,NMRKS(1,2),HAMIL,NDET,1,G1,.TRUE.,NBASISMAX,.FALSE.)
      |                                                                 1
Error: Type mismatch between actual argument at (1) and actual argument at (2) (COMPLEX(8)/REAL(8)).`

Probably due to the version of GCC.

**Comment by mcocdawc** [comment]
Thank you for reporting this bug.
Are you compiling in debug mode?

If you don't need to work with a complex implementation (i.e. you don't do relativistic or magnetic calculations)
you can just compile and use the implementations with real numbers
`make neci dneci`.

We are in the process of cleaning the implicit type conversions.

**Comment by Standazwicky** [comment]
Thanks for your reply and help.
